[package]
name = "heeler-project"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
heeler-graph = { path = "../heeler-graph" }
heeler-commands = { path = "../heeler-commands" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
